In [16]:
import pandas as pd

# ---------------------------------------------------------------------------
# a. Carga de datos desde un archivo CSV
# ---------------------------------------------------------------------------
print("--- a. Cargando datos desde el archivo CSV ---")

# Se importa el conjunto de datos desde el archivo CSV especificado
#
df = pd.read_csv('LigaEspanola2023-2024-Resultados.csv', delimiter=';')

# Se realiza una limpieza inicial de los nombres de las columnas
df.columns = df.columns.str.strip()
print("Datos cargados exitosamente.")
print("-" * 60)


# ---------------------------------------------------------------------------
# b. Exploración y limpieza de datos
# ---------------------------------------------------------------------------
print("--- b. Exploración y limpieza de datos ---")

# Muestra las primeras 10 filas del DataFrame
print("\nPrimeras 10 filas del DataFrame:")
display(df.head(10))

# Verifica los tipos de datos y la presencia de valores nulos
print("\nInformación general y conteo de nulos:")
df.info()

# Limpieza básica: renombrar columnas y manejar nulos
df.rename(columns={
    'HomeTeam': 'EquipoLocal',
    'AwayTeam': 'EquipoVisitante',
    'HG': 'GolesLocal',
    'AG': 'GolesVisitante',
    'Res': 'Resultado'
}, inplace=True)

df.fillna({'GolesLocal':0}, inplace=True)
df.fillna({'GolesVisitante':0}, inplace=True)
df.fillna({'Resultado':'Desconocido'}, inplace=True)

print("\nLimpieza básica realizada: columnas renombradas y nulos gestionados.")
print("-" * 60)


# ---------------------------------------------------------------------------
# c. Transformación y creación de nuevas columnas
# ---------------------------------------------------------------------------
print("--- c. Transformación y creación de nuevas columnas ---")
df_transformado = df.copy()

# Crea una nueva columna que represente el total de goles del partido
df_transformado['TotalGoles'] = df_transformado['GolesLocal'] + df_transformado['GolesVisitante']
print("2. Columna 'TotalGoles' creada.")

print("\nDataFrame con las nuevas transformaciones:")
display(df_transformado[['Date', 'EquipoLocal', 'EquipoVisitante', 'TotalGoles']].head())
print("-" * 60)


# ---------------------------------------------------------------------------
# d. Exportación de datos limpios a CSV
# ---------------------------------------------------------------------------
print("--- d. Exportación de datos limpios a CSV ---")

# Exporta el DataFrame limpio y transformado a un nuevo archivo CSV
#
df_transformado.to_csv('liga_espanola_limpio.csv', index=False)
print("DataFrame limpio guardado exitosamente como 'liga_espanola_limpio.csv'")
print("-" * 60)

--- a. Cargando datos desde el archivo CSV ---
Datos cargados exitosamente.
------------------------------------------------------------
--- b. Exploración y limpieza de datos ---

Primeras 10 filas del DataFrame:

,Round,Date,HomeTeam,AwayTeam,HG,AG,TotalGoals,Res
0,33,29-04-2024 0:00,Barcelona,Valencia,4,2,6,Home
1,33,28-04-2024 0:00,Betis,Sevilla,1,1,2,Tie
2,33,28-04-2024 0:00,Villarreal,Rayo Vallecano,3,0,3,Home
3,33,28-04-2024 0:00,Granada CF,Osasuna,3,0,3,Home
4,33,28-04-2024 0:00,Cadiz CF,Mallorca,1,1,2,Tie
5,33,27-04-2024 0:00,Atl. Madrid,Ath Bilbao,3,1,4,Home
6,33,27-04-2024 0:00,Alaves,Celta Vigo,3,0,3,Home
7,33,27-04-2024 0:00,Almeria,Getafe,1,3,4,Away
8,33,27-04-2024 0:00,Las Palmas,Girona,0,2,2,Away
9,33,26-04-2024 0:00,Real Sociedad,Real Madrid,0,1,1,Away

Información general y conteo de nulos:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Round       330 non-null    int64
 1   Date        330 non-null    object
 2   HomeTeam    330 non-null    object
 3   AwayTeam    330 non-null    object
 4   HG          330 non-null    int64
 5   AG          330 non-null    int64
 6   TotalGoals  330 non-null    int64
 7   Res         330 non-null    object
dtypes: int64(4), object(4)
memory usage: 20.8+ KB

Limpieza básica realizada: columnas renombradas y nulos gestionados.
------------------------------------------------------------
--- c. Transformación y creación de nuevas columnas ---
2. Columna 'TotalGoles' creada.

DataFrame con las nuevas transformaciones:

              Date EquipoLocal EquipoVisitante  TotalGoles
0  29-04-2024 0:00   Barcelona        Valencia           6
1  28-04-2024 0:00       Betis         Sevilla           2
2  28-04-2024 0:00  Villarreal  Rayo Vallecano           3
3  28-04-2024 0:00  Granada CF         Osasuna           3
4  28-04-2024 0:00    Cadiz CF        Mallorca           2

------------------------------------------------------------
--- d. Exportación de datos limpios a CSV ---
DataFrame limpio guardado exitosamente como 'liga_espanola_limpio.csv'
------------------------------------------------------------